# Generated by Django 6.0.2 on 2026-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_display_name_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends only')], default='public', max_length=20),
        ),
    ]
